application: k2gatsby
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:
- url: /api/.*
  script: application.app

- url: /
  static_files: compiled/index.html
  upload: compiled/.*

- url: /([0-9a-zA-z_-]*)
  static_files: compiled/\1/index.html
  upload: compiled/.*

- url: /(.*)
  static_files: compiled/\1
  upload: compiled/.*

skip_files: |
   ^(.*/)?(
   (app\.yaml)|
   (app\.yml)|
   (index\.yaml)|
   (index\.yml)|
   (#.*#)|
   (.*~)|
   (.*\.py[co])|
   (.*/RCS/.*)|
   (\..*)|
   (plugins\/.*)|
   (^pages\/.*)|
   (partials\/.*)|
   (posts\/.*)|
   (themes\/.*)|
   (^widgets\/.*)|
   )$
