---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://gap.samdeha.com

posts:
  permalink: /:categories/:title/
  summary_lines: 10
  latest: 10

pages:
  permalink: 'pretty'